sudo: false
language: node_js
node_js: stable

git:
  depth: 2

branches:
  only:
    - dev

before_install:
  - npm install

script:
  - npm run test

# after_script:
#   - npm run coverage
#   - npm run report
